use_frameworks!

target 'FFCategoryKit_Example' do
  pod 'FFCategoryKit', :path => '../'

  target 'FFCategoryKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
